### ISSUE TITLE
faster blank

### ISSUE THREAD

**Issue by kostya** [phoffer/crystalized_ruby#2]
try this blank implementation, this should be much faster.
https://github.com/crystal-lang/crystal/pull/1299/files

**Comment by phoffer** [comment]
Thanks @kostya! I implemented this, but I'm not seeing improved performance. I have a test script and the results at [this gist](https://gist.github.com/phoffer/5f09da6b57d23af842ed3cf2fda423f5). Would you mind checking if I am missing something?

**Comment by kostya** [comment]
```
crystal blank.cr --release

timing blank methods
---- " " ----
time old: 00:00:13.6915960
time new: 00:00:04.4942170
---- "\t\n" ----
time old: 00:00:14.3648220
time new: 00:00:04.5983810
---- " " ----
time old: 00:00:15.1577780
time new: 00:00:04.4028640
---- "a" ----
time old: 00:00:15.3445730
time new: 00:00:04.3959760
---- "a " ----
time old: 00:00:14.3955100
time new: 00:00:04.4290940
---- "" ----
time old: 00:00:14.6836820
time new: 00:00:04.3820810
```

**Comment by phoffer** [comment]
Ahh yes I forgot to use the `--release` flag. Thank you!

**Comment by phoffer** [comment]
Fixed in https://github.com/phoffer/inflector.cr/commit/5d4eb19bee5192c916313863bd7d406e64b92cd8
