### ISSUE TITLE
State of a gem?

### ISSUE THREAD

**Issue by stereobooster** [phoffer/crystalized_ruby#8]
Hi there.

I'm curious what is the state of this work. Plus I'm interested how final result should look like. For example if I take [ruby-mime-types](https://github.com/mime-types/ruby-mime-types) gem, can I compile it with crystal without much changes?

**Comment by phoffer** [comment]
I apologize for the delayed response!

This project is in hibernation for the time being. There have been some changes to recent Crystal versions that will require re-writing how the compilation works. Also, the Crystal team has added `DSL for writing Ruby extensions` to their [roadmap](https://github.com/crystal-lang/crystal/wiki/Roadmap), so I'm waiting to see how they want to do that to really dig back in.

As for you question about ruby-mime-types, that's not quite what this project is designed for. To compile that to Crystal, you'll need to translate the codebase to Crystal. For some projects, this isn't much work (see [inflector.cr](https://github.com/phoffer/inflector.cr)). For other projects, it may be a lot of work. It just depends on how it was built.

This project is to allow use of Crystal for native extensions, the same that C is used and that Rust has been experimentally used more recently.

I hope this helps, let me know if you have any other questions.

**Comment by stereobooster** [comment]
Thanks for the detailed answer
